### ISSUE TITLE
iOS 8.4.1 - Dropdown issue in iPad Safari

### ISSUE THREAD

**Issue by kathiravanmanimozhi** [joeldbirch/superfish#143] opened 2015-08-21 04:40 UTC
Hello,
We use SuperFish dropdown menu for our application. Till the previous version of iOS in iPad, it was working fine. For the users upgraged the iOS to 8.4.1, on the tap of Menu Item, the dropdown just appear and disappear immediately. This issue occurs only on iPad with iOS version 8.4.1.

Our Production website is down because of this. Please help us with a solution.

**Comment by joeldbirch** [comment] 2015-08-21 09:29
Please confirm you are seeing the same bug with the examples at http://users.tpg.com.au/j_birch/plugins/superfish/examples/

**Comment by kathiravanmanimozhi** [comment] 2015-08-21 15:55
No Joel. I'm not seeing the same issue in the examples.

If I remove the reference to superfish.min.js from my master file, the click shows the dropdown and doesn't disappear. Though, my text is wrapped.

Does iOS assume the touch as double-tap?

I am trying to setup a jsfiddle for you and unsuccessful so far. Is there any other way that I can share the behavior with you (share the actual files)?

I tried with the latest version of Superfish as well.

**Comment by joeldbirch** [comment] 2015-08-21 16:06
I think we can be 90% sure the issue is being caused by something on your site. If you could put your site back online maybe I'll have a moment over the weekend to see if I notice anything. It seems quite extreme to take it offline anyway, doesn't it?

**Comment by kathiravanmanimozhi** [comment] 2015-08-21 17:08
Our dev site can help. You would need credentials to login though. Could we work with that?

Much appreciated.

**Comment by joeldbirch** [comment] 2015-08-21 17:18
Okay. My email is my GitHub name at gmail dot com. Cheers.

**Comment by kathiravanmanimozhi** [comment] 2015-08-21 17:28
Is there a way to connect over a screen-share session with you, Joel? I
understand your time is valuable. Wanted to check with you though. Just
because it's the enterprise application and I am not able to setup a light
version of it to showcase the issue.

Please let me know.

**Comment by kathiravanmanimozhi** [comment] 2015-08-21 17:42
Is there a way to connect over a screen-share session with you, Joel? I understand your time is valuable. Wanted to check with you though. Just because it's the enterprise application and I am not able to setup a light version of it to showcase the issue.

Please let me know.

**Comment by joeldbirch** [comment] 2015-08-21 19:24
Sorry, it's the middle of the night here and the weekend. I'll maybe have a look if I can fit it in, but otherwise I'll be available for paid work through the week. This doesn't look like a bug with the plugin so I may close this issue soon.

**Comment by joeldbirch** [comment] 2015-09-01 05:08
Hello. I have looked into this and it appears that Apple may have removed their early solution for supporting hovers on touch devices. It's likely that you are using a very old version of Superfish (most probably 1.4.8) which doesn't have true touch support. You will need to update to the latest version (1.7.6) as well as hoverIntent (which comes packaged with Superfish).

This is why a test site is required when submitting bugs. I could have noticed the cause of your issue within 5 minutes.

Hope this helps.

**Closed** 2015-12-10 03:31 UTC
